# Generated by Django 5.1.4 on 2025-08-02 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pickuptransaction_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuptransaction',
            name='cluser_aera',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='cluser_aera',
        ),
        migrations.RemoveField(
            model_name='pickuptransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pickuptransaction',
            name='shop_owner',
        ),
        migrations.RemoveField(
            model_name='pickupwastdata',
            name='pickup_transaction',
        ),
        migrations.RemoveField(
            model_name='pickupwastdata',
            name='waste_type',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wastetype',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('withdrawal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='clusteraera',
        ),
        migrations.DeleteModel(
            name='PickupTransaction',
        ),
        migrations.DeleteModel(
            name='PickupWastData',
        ),
        migrations.DeleteModel(
            name='ShopOwner',
        ),
        migrations.DeleteModel(
            name='WasteType',
        ),
    ]
